export const CHANGE_SELECTED_TAB = 'CHANGE_SELECTED_TAB';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';
export const OPEN_DIALOG = 'OPEN_DIALOG';

export const ADD_TODO = 'ADD_TODO';
export const ADD_TODO_LOADING = 'ADD_TODO_LOADING';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_ERROR = 'ADD_TODO_ERROR';

export const CHECK_TODO = 'CHECK_TODO';
export const CHECK_TODO_LOADING = 'CHECK_TODO_LOADING';
export const CHECK_TODO_SUCCESS = 'CHECK_TODO_SUCCESS';
export const CHECK_TODO_ERROR = 'CHECK_TODO_ERROR';

export const DELETE_TODO = 'DELETE_TODO';
export const DELETE_TODO_LOADING = 'DELETE_TODO_LOADING';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_ERROR = 'DELETE_TODO_ERROR';

export const GET_TODOS_LIST = 'GET_TODOS_LIST';
export const GET_TODOS_LIST_LOADING = 'GET_TODOS_LIST_LOADING';
export const GET_TODOS_LIST_SUCCESS = 'GET_TODOS_LIST_SUCCESS';
export const GET_TODOS_LIST_ERROR = 'GET_TODOS_LIST_ERROR';

export const GET_TODOS_LIST_BY_PAGE = 'GET_TODOS_LIST_BY_PAGE';
export const GET_TODOS_LIST_BY_PAGE_LOADING = 'GET_TODOS_LIST_BY_PAGE_LOADING';
export const GET_TODOS_LIST_BY_PAGE_SUCCESS = 'GET_TODOS_LIST_BY_PAGE_SUCCESS';
export const GET_TODOS_LIST_BY_PAGE_ERROR = 'GET_TODOS_LIST_BY_PAGE_ERROR';

export const FLUSH_TODOS_LIST = 'FLUSH_TODOS_LIST';

// export const UPDATE_TODO = 'UPDATE_TODO';
